name: coverage

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox virtualenv

      - name: Test build with coverage
        run: "tox -e cov-report"

      - name: Send coverage report to codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
